EnigmaVSSUT/Induction-2025

Open_Source/Task/Remit_Patra/README.md
=> Remit's first commit

Open_Source/Task/Sambhav_Shadangi/README.md
Hello My name is Sambhav Shadangi , I am from the branch of Computer Science and Engineering and this was my first commit for the induction process
=> First commit

Open_Source/Task/Subhashree Sahu/README.md
=> Assignment-1 ITP : Subhashree Sahu

Open_Source/Task/Vipul_Krishna_Gahir/README.md
Information File of Vipul Krishna Gahir, 2402081021, CSE AIML added
=> Vipul Krishna Gahir Info file

Open_Source/Task/Yograj_Patel/README.md
=> Added details

Open_Source/Task/Abhijit_Sahu/README.md
I have completed the 1st week task of git bash.
=> Git Bash Task completed

Open_Source/Task/Anushree_Mohanty/README.md
I added a new README.md file in the folder named *"Anushree_Mohanty"* as per the given task for the Induction process of Enigma.
=> Added a new README.md file 

Open_Source/Task/Vidyoshah_Behera/README.md
**Open Source Task Completed**
=> Task 1 completed

Open_Source/Task/sameer_raja/README.md
=> Completed Open Source Task

Open_Source/Task/Shaswat_Ranjan_Hota/README.md
=> Task-1 : Shaswat H

Open_Source/Task/Shubham_Sethi/README.md
=> OPEN SOURCE TASK COMPLETED

Charchit/README.md, Open_Source/Task/Charchit/README.md
I HAVE ONCE COMPLETED THE PROJECT FROM MY SIDE AT#74 BUT THERE WERE SOME ERRORS .SO MY MENTOR ADVISED ME TO REPEAT THE PROCESS AGAIN  .I HOPE  THIS TASK  GETS COMPLETED.
=> Added Charchit profile and README.md in Task folder

Open_Source/Task/Sourav_Naik/Readme.md
=> Task 1 Sourav Naik

Open_Source/Task/Ch_Abhijeet_Achary/README.md
=> task 1 Abhijeet

Open_Source/Task/Aditi Saraph/README.md
=> add readme file

Open_Source/Task/Somesh_Behera/README.md, Open_Source/Task/Somesh_Chandra_Behera
=> Somesh Chandra Behera

Open_Source/Task/Niharika/READ.md
=> completed the task

Open_Source/Task/Samitesh_Panda/README.md
=> Samitesh Panda

Open_Source/Task/Aishwarya Priyadarshini Mallick/READ.md
=> add a passage

Open_Source/Task/Aayush_Patro/README.md
sorry for the late entry. was unable to complete the task due to health issues
=> Added README file
